
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'data_analytic_engineer_dwh_final_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'data_analytic_engineer_dwh_final_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  data_analytic_engineer_dwh_final_project:
    bronze:
      +materialized: table
      +schema: |
        {%- if  target.name == "dev" -%} bronze
        {%- elif target.name == "prod" -%} bronze
        {%- elif target.name == "stag" -%} bronze    
        {%- else -%} invalid_database
        {%- endif -%}
    silver:
      +materialized: table
      +schema: |
        {%- if  target.name == "dev" -%} silver
        {%- elif target.name == "prod" -%} silver
        {%- elif target.name == "stag" -%} silver    
        {%- else -%} invalid_database
        {%- endif -%}
    gold:
      +materialized: table
      +schema: |
        {%- if  target.name == "dev" -%} gold
        {%- elif target.name == "prod" -%} gold
        {%- elif target.name == "stag" -%} gold    
        {%- else -%} invalid_database
        {%- endif -%}
