data_analytic_engineer_dwh_final_project:
  outputs:
    dev:
      dataset: data_analytic_engineer_dwh_final_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: service-account
      priority: interactive
      project: class-data-analytics-engineer
      threads: 1
      type: bigquery
      keyfile: "{{ env_var('BQ_SA_PATH') }}"
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
